paicoding:
  login:
    zsxq:
      api: https://wx.zsxq.com/connector/crm/identify_member.html
      appId: 666
      groupNumber: 666
      secret: 666
      redirectUrl: https://paicoding.com/login/zsxq/callback
    wx:
      # 生产环境，使用服务号登录
      loginQrType: SERVICE_ACCOUNT # SUBSCRIPTION_ACCOUNT 表示普通的公众号登录  SERVICE_ACCOUNT 表示服务号关注登录
      appId: wx9096eb1b2a3f63e4
      appSecret: 公众号
      qrCodeImg: ${view.site.contactMeWxQrCode}
      qrCodeLogo: ${view.site.websiteLogoUrl}
      securityCheckToken: # 为空，表示不对微信回调的接口进行校验